### ISSUE TITLE
No cache hit since 1.7.0; key too specific

### ISSUE THREAD

**Issue by adri** [shivammathur/cache-extensions#23]
**Describe the bug**
In this [commit](https://github.com/shivammathur/cache-extensions/commit/b0f769600b1864e6f42ba5889006dda161527791#diff-9c46790727c431db6a23a5e9e6131280e435089fccbfc4b4070ca369e8540e02R96
) the cache key was changed.

It seems to be that this is too specific as every job in my workflow now uses a different key.
Should the job maybe be removed from the key? Or do I need to hardcode an ID per job?

**Version**
- [x] I have checked releases and the bug exists in the latest patch version of `v1`.
https://github.com/shivammathur/cache-extensions/releases/tag/1.7.0

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Comment by shivammathur** [comment]
Different jobs should have a different cache. This was done as jobs running in parallel with the same cache key might conflict with each other.

The job names remain constant between different runs, so cache should be hit, can you link me to 2 subsequent workflow runs where the cache was not hit on the second run.

**Comment by shivammathur** [comment]
I ran a test and it works, the cache is now unique for each job but it was hit on the second run.

Without cache - https://github.com/shivammathur/test-setup-php/runs/4595272782?check_suite_focus=true
With cache - https://github.com/shivammathur/test-setup-php/runs/4595318539?check_suite_focus=true
