### ISSUE TITLE
dependabot wants to downgrade from 1.9.1 => 1.10.0

### ISSUE THREAD

**Issue by heddn** [shivammathur/cache-extensions#41]
**Describe the bug**

Due to semver, we need a version tagged after 1.10.0.

![image](https://github.com/shivammathur/cache-extensions/assets/1581734/1c82a729-34c2-4cf9-a517-9476d8fa6d3c)

**Version**
- [ ] I have checked releases and the bug exists in the latest patch version of `v1`.
- [ ] `v2`
- [x] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**

**PHP versions**

**To Reproduce**

**Expected behavior**

**Screenshots/Logs**

**Additional context**

**Are you willing to submit a PR?**

**Comment by heddn** [comment]
This is particularly aggravating due to the impending sunset to node.js 16 actions:

![image](https://github.com/shivammathur/cache-extensions/assets/1581734/c396c788-caef-497b-91a2-8a654e0bf15d)

**Comment by shivammathur** [comment]
Fixed in https://github.com/shivammathur/cache-extensions/commit/8754e0a21eba2e3e2594909e457fddec3d88d455
